version: 2
jobs:
  build:
    docker:
      - image: cimg/node:20.16.0
    parallelism: 1
    working_directory: ~/eclimov/mdshop-ui-admin
    steps:
      - checkout
      - attach_workspace:
          at: ~/eclimov/mdshop-ui-admin
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: [dist]

  deploy:
#    docker:
#      - image: docker:18.05.0-ce-git # TODO: remove this step?
    parallelism: 1
    working_directory: ~/eclimov/mdshop-ui-admin
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/eclimov/mdshop-ui-admin
      - run:
          name: Deploy to DigitalOcean
          command: |
            ssh -o "StrictHostKeyChecking no" $DEPLOY_USER@$DEPLOY_HOST bash -c "
              cd /root
              mkdir -p mdshop-ui-admin
              rm -rf mdshop-ui-admin/*"
            scp -r dist $DEPLOY_USER@$DEPLOY_HOST:/root/mdshop-ui-admin

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          context: mdshop # The context shares common environment variables
          requires:
            - build
          filters:
            branches:
              only: master
